---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to my research website. 

To see my inference of selection using the poisson random field model, click here [link](simple_inference_PRF.html)  
To see my simple inference of W using STAN, click here [link](simple_stan_inference.html)   
To see the results of data processing, click here [link](CS_results.html)   
To see the results of my data processing from the GWAS Atlas, click here [link](GWAS_ATLAS_results.html)  
To see the results of my UKBB vs BBJ data processing, click here [link](BBJvUKKBB.html)  
To see the results of PCA on 1kg data, click here [link](Stratification.html)   
To see the results of looking for stratification in GWAS summary statistics, click here [link](shift_GWAS_ATLAS.html)  
To see STAN inference, click here [link](STAN_model_strat.html)  
To see misc gwas processing, click here [link](misc_gwas.html)  
To see more GWAS processing, click here [link](strat_GWASs.html)


